#Set apiversion 1
apiVersion: v1
#Object type service
kind: Service
#Set name & labels
metadata:
  name: mongo
  labels:
    app: mongo
#Set ports & Selector
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongo
    tier: backend
  clusterIP: None