#Menggunakan v1
apiVersion: apps/v1
#Tipe jenis object Deployment
kind: Deployment


metadata:
  #Set name
  name: karsajobs
  #Set labels
  labels:
    app: karsajobs 

spec:
  #Replica hanya 1
  replicas: 1
  #Select Karsajobs
  selector:
    matchLabels: 
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      #Get the container
      containers:
        - name: karsajobs
          image: smamhtn/karsajobs:latest
          #Set port
          ports:
            - containerPort: 8080
          #Set port & DB
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_PASSWORD